#!/usr/bin/env bash
# Discharge the UNBOUNDED-ROUNDS inductive-invariant proof (Apalache, SMT).
# Unlike check-induction.sh (which fixes MaxRound), here round numbers are FREE
# INTEGERS generated by `Gen`; only the vote-configuration cardinality is bounded.
# See docs/audit/15-unbounded-rounds-verification.md.
set -euo pipefail
cd "$(dirname "$0")"
BIN=../tools/apalache/bin/apalache-mc
[ -x "$BIN" ] || ./fetch-apalache.sh
M=DDRConsensusUnbounded.tla
# arrays SMT encoding: far faster than the default on this Cardinality-heavy,
# Gen-built model, semantically identical.
C="--cinit=ConstInit --next=Next --smt-encoding=arrays"

echo "== typecheck =="
$BIN typecheck $M | grep -E "purrfect|OK|error" || true

echo "== (1) Init => IndInv =="
$BIN check $C --init=Init  --inv=IndInv    --length=0 $M | grep -E "no error|violated"
echo "== (2) IndInv => Agreement =="
$BIN check $C --init=CInit --inv=Agreement --length=0 $M | grep -E "no error|violated"
echo "== (3) IndInv /\\ Next => IndInv'  (inductive step, FREE-INT rounds) =="
$BIN check $C --init=CInit --inv=IndInv    --length=1 $M | grep -E "no error|violated"
